# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
      path: $(MAVEN_CACHE_FOLDER)
    displayName: 'Cache Maven dependencies'

  - task: Maven@4
    inputs:
      mavenPomFile: 'experiment-02-maven/pom.xml'
      goals: 'clean package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
    displayName: 'Maven Build & Test'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'experiment-02-maven/target'
      ArtifactName: 'drop'
    displayName: 'Publish Artifacts'
